spring:
  application:
    name: analytical_system
  config:
    import: "vault://v1/secret/data"
  cloud:
    vault:
      enabled: true
      authentication: TOKEN
      token: ${VAULT_TOKEN}
      scheme: http
      uri: http://0.0.0.0:8200/
      kv:
        backend: /secret/data
        kv-version: 1

  datasource:
    url: ${pgAnalyticalUrl}
    username: ${techUserName}
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console.enabled: true

server:
  port: 8081

# kafka
topicAUTO: analyticalserv
bootstrapServerConfig: "localhost:9092,localhost:9093,localhost:9094"

# postgres
pgAnalyticalUrl: "jdbc:h2:mem:analyticalevents"