spring:
  application:
    name: analytical_system


  datasource:
    url: jdbc:h2:mem:analyticalevents
    username: mike1
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console.enabled: true
server:
  port: 8081

topicAUTO: analyticalserv