spring:
  application:
    name: problmonitoring
  config:
    import: "vault://v1/secret/data"
  cloud:
    vault:
      enabled: true
      authentication: TOKEN
      token: ${VAULT_TOKEN}
      scheme: http
      uri: http://0.0.0.0:8200/
      kv:
        backend: /secret/data
        kv-version: 1

# kafka
topicMonitoring: "monitoringserv"
topicAUTO: "analyticalserv"
bootstrapServerConfig: "localhost:9092,localhost:9093,localhost:9094"